accounts/urls.py
from django.conf.urls import *
from django.contrib.auth import views as auth_views
from django.views.generic.simple import redirect_to


urlpatterns = patterns ('accounts.views',
        url (r'^$', redirect_to, {'url': '/'}),
    url (r'^register/$', 'register'),
    url (r'^login/$', 'login_view'),
    url (r'^logout/$', 'logout_view'),
    url (r'^change_password/$', auth_views.password_change, name='auth_password_change'),
    url (r'^change_password/done/$', auth_views.password_change_done, name='auth_password_change_done'),
    #url (r'^reset_password/$', 'reset_password'),

    url (r'^users/$', 'find_user'),
    url (r'^users/(?P<username>[^/]+)/$', 'user_view'),

    url (r'^notification/$', 'request_note'),

)

fw3e11_msc_project/urls.py
from django.conf.urls import patterns, include, url

from django.views.generic.simple import direct_to_template
from django.contrib.auth.views import password_reset

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url (r'^wikiforum/', include ('wikiforum.urls')),
    url (r'^accounts/', include ('accounts.urls')),
    url (r'^mindview/', include ('mindview.urls')),
    url (r'^$', direct_to_template,
        {'template': 'index.html'}),
    # Examples:
    # url(r'^$', 'fw3e11_msc_project.views.home', name='home'),
    # url(r'^fw3e11_msc_project/', include('fw3e11_msc_project.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

wikiforum/urls.py
from django.conf.urls import *
from django.views.generic.simple import redirect_to

urlpatterns = patterns ('wikiforum.views',
        url (r'^$', redirect_to, {'url': '/wikiforum/search/'}),
    url (r'^search/$', 'search'),

        url (r'^posts/$', redirect_to, {'url': '/'}),
    url (r'^posts/(?P<post_id>[^/]+)/edit/$', 'post_edit'),
    url (r'^posts/(?P<post_id>[^/]+)/reply/$', 'post_reply'),
    url (r'^posts/(?P<post_id>[^/]+)/save/$', 'post_save'),
    url (r'^posts/(?P<post_id>[^/]+)/$', 'post_view'),
    url (r'^posts/(?P<post_id>[^/]+)/edit/history/$', 'history_view'),
    
    url (r'^tags/(?P<tag_name>[^/]+)/$', 'tag_view'),
    
    url (r'^search/request/$', 'request_test'),
    url (r'^search/get_all_title/$', 'get_all_title'),
    url (r'^search/get_all_tags/$', 'get_all_tags'),

    url (r'^posts/(?P<post_id>[^/]+)/comment/save/$', 'comment_save'),
    url (r'^posts/(?P<post_id>[^/]+)/comment/(?P<comment_id>[^/]+)/delete/$', 'comment_delete'),

    url (r'^posts/(?P<post_id>[^/]+)/edit/history/(?P<history_id>[^/]+)/$', 'history_rollback'),

    url (r'^posts/(?P<post_id>[^/]+)/edit/history/(?P<history_id>[^/]+)/accept/$', 'request_accept'),
    url (r'^posts/(?P<post_id>[^/]+)/edit/history/(?P<history_id>[^/]+)/deny/$', 'request_deny'),
)

wikiforum/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Forum (models.Model):
    name = models.CharField (max_length = 200, primary_key = True)
    
    def __unicode__ (self):
        return self.name

class Post (models.Model):
    forum = models.ForeignKey (Forum)
    title = models.CharField (max_length = 200)
    body = models.TextField ()
    body_html = models.TextField ()
    tags = models.ManyToManyField ('Tag')
    modified = models.DateTimeField ('Modified', auto_now_add = True)
    modified_by = models.ForeignKey (User) # this is always the first creator
    pre_post = models.ForeignKey ('self', blank = True, null = True, related_name = '+')
    is_secure = models.BooleanField (default = False)

    def __unicode__ (self):
        return self.title

class Comment (models.Model):
    post = models.ForeignKey (Post)
    content = models.TextField ()
    modified = models.DateTimeField ('Modified', auto_now_add = True)
    modified_by = models.ForeignKey (User)

    def num (self):
        return sum ([t.num() for t in self.post_set.all ()])

class Tag (models.Model):
    name = models.CharField (max_length = 200, primary_key = True)

    def __unicode__ (self):
        return self.name

class History (models.Model):
    post = models.ForeignKey (Post)
    title = models.CharField (max_length = 200)
    body = models.TextField ()
    modified = models.DateTimeField ('Modified', auto_now_add = True)
    modified_by = models.ForeignKey (User)
    is_accepted = models.BooleanField ()
    is_processed = models.BooleanField (default = False)
    processed_by = models.ForeignKey (User, blank = True, null = True, related_name = '+')
    current_version = models.BooleanField (default = False)

    def __unicode__ (self):
        return "History of \"" + self.post.title + "\""

wikiforum/views.py
# Create your views here.

from wikiforum.models import *
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext

from django.contrib.auth.decorators import login_required
from django.db import transaction
import json

forum = Forum.objects.get_or_create (name = "fw3e11-forum")

from django import forms
class SearchForm (forms.Form):
    search_text = forms.CharField (label=False,widget=forms.TextInput(attrs={'data-provide':'typeahead','autocomplete':'off', 'placeholder': 'Search posts by title or content'}))

def new_pk ():
    if Post.objects.all ():
        last_pk_obj = Post.objects.all ().order_by ('-pk') [0]
        pk = last_pk_obj.pk + 1
    else:
        pk = 1
    return pk

def to_html (body):
    body_html = body.replace("\r\n", "<br/>")
    body_html = body.replace("\n", "<br/>")
    body_html = body.replace("\r", "<br/>")
    return body_html


########################################
def request_test (request):
    # print dir(RequestContext)
    context_instance = RequestContext (request)
    print context_instance.dicts[2]['user']
    # which will return 'test' -- a username
########################################


@login_required
def get_all_title (request):
    try:
        message = {}
        title = []
        title_list = [ttl.title for ttl in Post.objects.all ()]
        title_list = list (set (title_list)) # remove duplicated titles
        message ['items'] = title_list
        data = json.dumps (message)
        return HttpResponse (data, mimetype="application/json")
    except Exception as e:
        print e
        return HttpResponse ("Error")

@login_required
def get_all_tags (request):
    try:
        message = {}
        tags = []
        tag_list = [tgs.name for tgs in Tag.objects.all ()]
        message ['items'] = tag_list
        data = json.dumps (message)
        return HttpResponse (data, mimetype="application/json")
    except Exception as e:
        print e
        return HttpResponse ("Error")


# Search
@login_required
def search (request):
    if request.method == 'POST':
        form = SearchForm (request.POST)
        if not form.is_valid ():
            return render_to_response ("wikiforum/search.html", locals (), context_instance = RequestContext (request))
        else:
            search_text = form.cleaned_data ['search_text']
            title_result = Post.objects.filter (title__icontains = search_text)
            # print type(title_result)
            body_result = Post.objects.filter (body__icontains = search_text)
            new_post = Post (pk = new_pk ())
            return render_to_response ("wikiforum/search.html", locals (), context_instance = RequestContext (request))
    form = SearchForm ()
    return render_to_response ("wikiforum/search.html", locals (), context_instance = RequestContext (request))

# Edit
@login_required
def post_edit (request, post_id):
    # draw existing data, to be modified
    try:
        post = Post.objects.get (pk = post_id)
        title = post.title
        body = post.body
        body_html = post.body_html
        tags = " ".join ([tag.name for tag in post.tags.all ()])
    # New Post
    except Post.DoesNotExist:
        title = ""
        body = ""
        body_html = ""
        tags = ""
    return render_to_response ("wikiforum/edit.html", locals (), context_instance = RequestContext (request))

# Reply
@login_required
def post_reply (request, post_id):
    post = Post.objects.get (pk = post_id)
    u = User.objects.get (username = request.session ['username'])
    new_post = Post (pk = new_pk (),
            forum = forum [0],
            title = "re: " + post.title,
            body = "",
            body_html = "",
            modified_by = u,
            pre_post = post)
    request.session ['pre_post'] = post.pk
    return render_to_response ("wikiforum/reply.html", locals (), context_instance = RequestContext (request))

# Save
def post_save (request, post_id):
    title = request.POST ['title']
    body = request.POST ['body']
    try:
        is_secure = request.POST ['is_secure']
    except: pass
    tag_list = []
    u = User.objects.get (username = request.session ['username'])
    if 'tags' in request.POST:
        tags = request.POST ['tags']
        tag_list = [Tag.objects.get_or_create (name = tag) [0] \
                for tag in tags.split ()]
    # Edit Exising Case
    try:
        post = Post.objects.get (pk = post_id)
        # title
        post.title = title
        # tags
        deleted_tags = set (post.tags.all ()) - set (tag_list)
        for tag in tag_list:
            post.tags.add (tag)
        for tag in deleted_tags:
            post.tags.remove (tag)

        post.save ()
        # sid = transaction.savepoint ()
        # body
        if post.body == body:
            return HttpResponseRedirect ("/wikiforum/posts/" + post_id + "/")
        body_html = to_html (body)

        post.body = body
        post.body_html = body_html
        # textarea
        #re.sub("\r", "<br/>", post.body)
                # ########
        if post.is_secure == True:
            if u.is_superuser or u == post.modified_by:
                post.save ()
                history = History.objects.create (post = post, title = title, body = post.body, modified_by = u, is_accepted = True, current_version = True)
                hcs = History.objects.filter (post = post, current_version = True)
                for hc in hcs:
                    hc.current_version = False
                    hc.save ()
                history.current_version = True
                history.save ()
            else:
                History.objects.create (post = post, title = title, body = post.body, modified_by = u, is_accepted = False)
        else:
            post.save ()
            history = History.objects.create (post = post, title = title, body = post.body, modified_by = u, is_accepted = True, current_version = True)
            hcs = History.objects.filter (post = post, current_version = True)
            for hc in hcs:
                hc.current_version = False
                hc.save ()
            history.current_version = True
            history.save ()

    # Post New Case
    except Post.DoesNotExist:
        # reply case
        try:
            pre_post = Post.objects.get (pk = request.session ['pre_post'])
            try:
                post = Post (title = "re: " + pre_post.title,
                        body = "",
                        body_html = "",
                        forum = forum [0],
                        modified_by = u,
                        pre_post = pre_post,
                        is_secure = is_secure)
            except:
                post = Post (title = "re: " + pre_post.title,
                        body = "",
                        body_html = "",
                        forum = forum [0],
                        modified_by = u,
                        pre_post = pre_post,
                        is_secure = False)
        # create case
        except KeyError:
            try:
                post = Post (title = "New post",
                        body = "",
                        body_html = "",
                        forum = forum [0],
                        modified_by = u,
                        is_secure = is_secure)
            except:
                post = Post (title = "New post",
                        body = "",
                        body_html = "",
                        forum = forum [0],
                        modified_by = u,
                        is_secure = False)
        # if
        if not title == "":
            post.title = title
        if body == "":
            return HttpResponse ("Body can't be null.")
        # textarea
        body_html = to_html (body)

        post.body = body
        post.body_html = body_html
        # ########
        post.save ()
        History.objects.create (post = post, title = title, body = post.body, modified_by = u, is_accepted = True, current_version = True)
        # deal tags
        for tag in tag_list:
            post.tags.add (tag)
        try:
            del request.session ['pre_post']        
        except:
            pass
    # history part moved
    return HttpResponseRedirect ("/wikiforum/posts/" + post_id + "/")

# View
@login_required
def post_view (request, post_id):
    try:
        post = Post.objects.get (pk = post_id)
        body_html = post.body_html
        tags = post.tags.all ()
        related_next_posts = []
        comments = Comment.objects.filter (post = post)
        # if you want create new one
        u = User.objects.get (username = request.session ['username'])
        new_post = Post (pk = new_pk (),
            forum = forum [0],
            title = "re: " + post.title,
            body = "",
            body_html = "",
            modified_by = u) 
        ###############################
        if Post.objects.filter (pre_post_id = post.pk):
            related_next_posts = [p for p in Post.objects.filter (pre_post_id = post.pk)]

        try:
            Post.objects.get (pk = post.pre_post_id)
            related_pre_post = Post.objects.get (pk = post.pre_post_id)
            # print "pre: " + related_pre_post.title
        except Post.DoesNotExist:
            # print "pre: None"
            pass
        # pre_post is unique ####################
        return render_to_response ("wikiforum/view.html", locals (), context_instance = RequestContext (request))
    except Post.DoesNotExist:
        return HttpResponse ("Error! Post Does Not Exist.")

@login_required
def tag_view (request, tag_name):
    try:
        tag = Tag.objects.get (name = tag_name)
        posts = tag.post_set.all ()
    except:
        return HttpResponse ("No tag named" + tag_name)

templates/wikiforum/edit.html
{% extends "base.html" %}

{% block css %}
<style type="text/css">
    a #history {
        font-size: 16px;
        padding: 9px;
    }
    input.t {
        height: 20px;
        width: 250px;
        font-size: 16px;
        padding: 3px 2px;
        margin: 10px;
    }
    textarea {
        padding: 3px 2px;
        font-size: 15px;
    }
    .button {
        vertical-align: middle;
        background: none;
        border: none;
        size: 20px;
        font-size: 16px;
        padding: 2px 10px;
        margin: 10px;
    }
    .button:hover {
        vertical-align: middle;
        background: none;
        border: none;
        size: 20px;
        font-size: 16px;
        font-weight: bold;
        cursor: pointer;
        padding: 2px 10px;
    }
    /**/
    input, textarea {
        width: 400px;
    }
    textarea {
        height: auto;
    }
</style>
{% endblock %}

{% block js %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
<script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-typeahead.js"></script>
<script type="text/javascript">
    $(function () {
            var data_source = [];
            $.ajax({
                url: '/wikiforum/search/get_all_tags/',
                dataType: 'json',
                success: function(data) {
                data_source = data.items;
                var options = {source: data_source};
                $('#id_tags_input').typeahead(options);
                }
                });
            });
</script>
{% endblock %}

{% block title %}
{% if body == "" %}
    New Post
{% else %}
    Edit
{% endif %}
{% endblock %}

{% block content %}
<span><a id="history" href="history/">View History</a></span>
<form method="post" action="/wikiforum/posts/{{ post_id }}/save/">
    {% csrf_token %}
    Title: <input name="title" class="t" value="{{ title }}">
    <br />
    <textarea name="body" rows="10" cols="20">{{ body }}</textarea>
    <br />
    Tags: <input id="id_tags_input" name="tags" class="t" autocomplete="off" value="{{ tags }}">
    {% if body == "" %}
    <br />secure: <input type="checkbox" name="is_secure" value="is_secure">
    {% endif %}
    <input type="submit" class="button" value="Post" />
</form>
{% endblock %}

templates/wikiforum/history.html
{% extends "base.html" %}
{% block css %}
<style type="text/css">
    table {
        border: 1px solid #c0c0c0;
    }
    tr {
        border: 1px solid #c0c0c0;
    }
    tr#title {
        text-align: center;
    }
    tr.current-version {
        color: red;
        font-weight: bold;
    }
    td {
        border: 1px solid #c0c0c0;
        padding: 2px 4px;
    }
    td.rollback,
    td.status,
    td.clk
    {
        text-align: center;
    }
    .popover-title {
        padding: 0px 0px;
        line-height: 0;
        background-color: #fff;
        border-bottom: 0px solid #000;
        -webkit-border-radius: 0px 0px 0 0;
        -moz-border-radius: 0px 0px 0 0;
        border-radius: 0px 0px 0 0;
    }
    .popover .arrow {
        position: fixed;
    }

</style>
{% endblock %}

{% block js %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
<script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-tooltip.js"></script>
<script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-popover.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
            $('tr').hover(function(){
                $(this).css("color", "red");
                }, function(){
                $(this).css("color", "#000")
                });
            
            $('td.clk').click(function() {
                var tr_id = $(this).attr('id');
                $.ajax({
                    url: '/mindview/history/' + tr_id + '/',
                    dataType: 'json',
                    success: function (data) {
                    $('tr#'+tr_id).attr('data-content', data['items']);
                    $('#info'+tr_id).text(data['items']);
                    }
                    });
                });
            var isVisible = false;
            var clickedAway = false;
            $('td.clk').popover({placement:'right'}).click(function(e){
                $(this).popover('show');
                $(this).css("background", "#c0c0c0");
                isVisible=true;
                e.preventDefault();
                });
            $(document).click(function(e){
                if (isVisible & clickedAway) {
                    $('td.clk').popover('hide');
                    $('td.clk').css("background", "#fff");
                    isVisible = clickedAway = false;
                }
                else {
                    clickedAway=true;
                }
                });
        });
</script>
{% endblock %}

{% block title %}History for "{{ post_obj.title }}"{% endblock %}

{% block h1 %}History for <a href="../../">{{ post_obj.title }}</a>{% endblock %}

{% block content %}
{% if history_list %}
<table>
    <tr id="title">
        <td>User</td>
        <td>Time</td>
        <td>Status</td>
        <td class="rollback">Rollback</td>
        <td>Content</td>
    </tr>
    {% for history in history_list %}
    {% if not history.current_version %}
    <tr>
        <td>{{ history.modified_by }}</td>
        <td>{{ history.modified }}</td>
        {% if history.is_accepted %}
        <td class="status">Accepted{% if history.processed_by %} by <a href="/accounts/users/{{ history.processed_by.username }}/">{{ history.processed_by.username }}</a>{% endif %}</td>
        <td class="rollback"><a onClick="return confirm('Are you sure to rollback?');" href="{{ history.pk }}/">Rollback</a></td>
        {% elif history.is_processed %}
        <td class="status">Denied by <a href="/accounts/users/{{ history.processed_by.username }}/">{{ history.processed_by.username }}</a></td>
        <td class="rollback">N/A</td>
        {% else %}
        <td class="status"><a onClick="return confirm('Are you sure to accept?');" href ="{{ history.pk }}/accept/">Accept</a>&nbsp;or&nbsp;<a onClick="return confirm('Are you sure to deny?');" href ="{{ history.pk }}/deny/">Deny</a></td>
        <td class="rollback">N/A</td>
        {% endif %}
        <td class="clk" id="{{ history.pk }}" rel="popover" data-content="<p id='info{{ history.pk }}'></p>">click</td>
    </tr>
    {% else %}
    <tr id={{ history.pk }} class="current-version" rel="popover" data-content="<p id='info{{ history.pk }}'></p>">
        <td>{{ history.modified_by }}</td>
        <td>{{ history.modified }}</td>
        <td class="status">Current Version<br />Accepted{% if history.processed_by %} by <a href="/accounts/users/{{ history.processed_by.username }}/">{{ history.processed_by.username }}</a>{% endif %}</td>
        <td class="rollback">N/A</td>
        <td class="clk" id="{{ history.pk }}" rel="popover" data-content="<p id='info{{ history.pk }}'></p>">click</td>
    </tr>
    {% endif %}
    {% endfor %}
</table>
{% else %}
No history record! &nbsp;
<a href="../">BACK TO EDIT</a>
{% endif %}

<div class="popover fade right in">
    <div class="arrow"></div>
    <div class="popover-inner">
        <h3 class="popover-title"></h3>
        <div class="popover-content">
        </div>
    </div>
</div>
{% endblock %}

templates/wikiforum/reply.html
{% extends "base.html" %}

{% block css %}
<style type="text/css">
    input.t {
        height: 20px;
        width: 250px;
        font-size: 16px;
        padding: 3px 2px;
        margin: 10px;
    }
    textarea {
        padding: 3px 2px;
        font-size: 15px;
        width: 400px;
    }
    .button {
        vertical-align: middle;
        background: none;
        border: none;
        size: 20px;
        font-size: 16px;
        padding: 2px 10px;
    }
    .button:hover {
        vertical-align: middle;
        background: none;
        border: none;
        size: 20px;
        font-size: 16px;
        font-weight: bold;
        cursor: pointer;
        padding: 2px 10px;
    }
</style>
{% endblock %}

{% block title %}
Reply: {{ post.title }}
{% endblock %}

{% block content %}
<form method="post" action="/wikiforum/posts/{{ new_post.pk }}/save/">
    {% csrf_token %}
    Title: <input name="title" class="t" value={{ title }} >
    <br />
    <textarea name="body" rows="10" cols="20">{{ body }}</textarea>
    <br />
    Tags: <input name="tags" class="t" value={{ tags }} >
    <br />secure <input type="checkbox" name="is_secure" value="is_secure">
    <input type="submit" class="button" value="Reply" />
</form>
{% endblock %}

templates/wikiforum/search.html
{% extends "base.html" %}

{% block title %}Search Page{% endblock %}
{% block js %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
<script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-typeahead.js"></script>
<script type="text/javascript">
    $(function () {
            var data_source = [];
            $.ajax({
                url: '/wikiforum/search/get_all_title/',
                dataType: 'json',
                success: function(data) {
                data_source = data.items;
                var options = {source: data_source};
                $('#id_search_text').typeahead(options);
                }
                });
            });
</script>
{% endblock %}

{% block css %}
<style type="text/css">
    form {
        padding: 0px 0px 10px 0px;
    }
    table {
        margin: -1 auto;
        padding: 10px 3px 3px 3px;
    }
    table th {
        display: none;
        /*visibility: hidden;*/
    }
    table input {
        height: 20px;
        width: 450px;
        font-size: 16px;
        padding: 5px 2px;
    }
    table .errorlist {
        list-style-type: none;
        float: right;
        padding: 8px 0px 0px 8px;
    }
    #submit {
        vertical-align: middle;
        background: none;
        border: none;
        size: 20px;
        font-size: 16px;
        padding: 2px 10px;
    }
    #submit:hover {
        vertical-align: middle;
        background: none;
        border: none;
        size: 20px;
        font-size: 16px;
        font-weight: bold;
        cursor: pointer;
        padding: 2px 10px;
    }
    h2 {
        padding: 0px;
    }
    div .result-list {
        padding: 0px 0px 0px 10px;
    }
    tr {
        padding: 3px;
    }
    td {
        list-style-type: none;
        padding: 2px 4px;
    }
    td.post_title:hover {
        border: 0 dotted #c0c0c0;
    }

</style>
{% endblock %}
{% block h1 %}Search{% endblock %}

{% block content %}

<form method="post" action="">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <!--label>&nbsp;</label-->
    <input id="submit" type="submit" value="Search" />
</form>

{% if search_text %}
<h2>Search result for <span class="search_text">{{ search_text }}</span></h2>
<div class="search-list">
    {% if title_result %}
    <h3>Search title:</h3>
    <table class="search_result">
        {% for result in title_result %}
        <tr>
            <td class="post_title"><a href="/wikiforum/posts/{{ result.pk }}/">{{ result.title}}</a></td>
            <td class="post_modified">{{ result.modified }}</td>
            <td class="post_modified_by"><a href="/accounts/users/{{ result.modified_by.username }}">{{ result.modified_by.username }}</a></td>
        </td>
        {% endfor %}
    </table>
    {% endif %}
</div>
<div class="search-list">
    {% if body_result %}
    <h3>Search body content:</h3>
    <table class="search_result">
        {% for result in body_result %}
        <tr>
            <td class="post_title"><a href="/wikiforum/posts/{{ result.pk }}/">{{ result.title}}</a></td>
            <td class="post_modified">{{ result.modified }}</td>
            <td class="post_modified_by"><a href="/accounts/users/{{ result.modified_by.username }}">{{ result.modified_by.username }}</a></td>
        </td>
        {% endfor %}
    </table>
    {% endif %}
</div>
<div class="search-list">
    {% if not title_result and not body_result %}
    <br />
    <p>No result found. <a href="/wikiforum/posts/{{ new_post.pk }}/edit/">New Post</a></p>
    {% else %}
    <br />
    All above are not what you want? &nbsp;<a href="/wikiforum/posts/{{ new_post.pk }}/edit/">New Post</a>
    {% endif %}
</div>
{% endif %}

{% endblock %}

templates/wikiforum/tag.html
{% extends "base.html" %}

{% block css %}
<style type="text/css">
    li {
        width: 98%;
        overflow-x: hidden;
        overflow-y: auto;
        padding: 2px;
    }
    
    ul {
        margin: 5px 0px;
    }
</style>
{% endblock %}

{% block title %}Posts tagged with {{ tag_name }}{% endblock %}

{% block h1 %}Post tagged with <span class="search_text">{{ tag_name }}</span>{% endblock %}

{% block content %}
<ul>
    {% for post in posts %}
    <li><a href="/wikiforum/posts/{{ post.id }}/">{{ post.title }}</a></li>
    {% endfor %}
</ul>
{% endblock %}